cmake/GetArch.cmake
cmake/metadata.cmake

So, I produced some interesting comments about the i386 -> x86_64 issue. But, I didn't actually fix the code. 
Sigh. While on it, remove some garbage in the tarball generated by CPack (why?)

Fix arch, clean up tarball garbage.

---

.circleci/config.yml
ci/circleci-build-raspbian-armhf.sh
ci/upload.sh.in

Also cuts some time from the slow raspbian-armhf builders.

Cleanup: drop redundant code.

---

cmake/PluginCompiler.cmake
cmake/PluginLibs.cmake
cmake/Targets.cmake

As discussed:
- Drop bugus /app from tarball
- Don't drop user's CMAKE_SHARED_LINKER_FLAGS
- Set up -fvisibility as applicable.
- A little more careful with windows paths with spaces (and mac, for sure)
- Drop debugging, clean up.
Feels reasonable safe, this one. New try: this should be the end of it, besides bugfixes. Unless you  have remarks or ideas.
I have been contemplating the idea to name the upload something like ShipDriver-5.2_ubuntu-18.04 instead of current ShipDriver_ubuntu-18.04. It would be a simple fix, basically a oneliner. Thoughts?
--a

Finalizing:  minor bugs and tweaks.

---

cmake/PluginInstall.cmake

I had a commit on my side which I didn't push in the PR. This was the reason this time. This commit should be the last one w r t make tarball.
Builds fine by me using this batch file:
```
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
set WXWIN=C:\wxWidgets-3.1.2
set wxWidgets_ROOT_DIR=%WXWIN%
set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
set PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;
set PATH=C:\Program Files\Cmake\bin;%PATH%
rem choco install poedit
rem download, unpack and install
rem http://opencpn.navnux.org/build_deps/OpenCPN_buildwin-4.99a.7z
rem into C:\wxWidgets-3.2.1
git clone  https://github.com/leamas/shipdriver_pi.git
cd shipdriver_pi
git fetch origin ms-install:ms-install
git …
```

win32: Sanitize install paths.

---

cmake/Targets.cmake

Turns out that the 'make pkg' problem was a simple bug.  'make pkg' works for me after this patch, would appreciate some feedback from you when you have time.

build: windows: NSIS package bugfix.

---

libs/jsoncpp/CMakeLists.txt

As heading says: Ensure that jsoncpp is statically linked on all tarballs. Unfortunately increases the  plugin library file size with about 250K.

Json: temporary fix for dysfunctional dynamic linkage to jsoncpp library 

---

ci/circleci-build-macos.sh

Still more more cruft to remove, and what's probably a rebasing error; the latter was such that it was really strange that cmake accepted it.
Anyway cleanup of circleci-build-macos. I have loaded the tarball into my MacOS VM, no crashes from start.

ci: macos: Cleanup.

---

cmake/Targets.cmake

As heading says: Either use just _cpack_ or _cpack -C config_. Current code basically collapses to  _cpack -C_ if config isn't defined. The horrifying fact is that cpack in this case silently fails without doing anything at all, at least on Linux.
Sigh.
Also: the generator expressions syntax is indeed awkward. Cannot to much about it...

cmake: Targets: Don't use -C flag if no <CONFIG> exists.

---

ci/circleci-build-macos.sh
cmake/PluginPackage.cmake
cmake/Targets.cmake

Seems like a strange rebasing error. Re-adding one part which definitely has been with us before.
Thanks for good bug report which made it possible to nail down the error in no time.
You can check the tarball yourself by downloading it, expand it and look for the file metadata.xml which lives in the top directory

cmake: target: Fix missing metadata in 'make tarball'.

---

cmake/PluginInstall.cmake
cmake/PluginLibs.cmake
cmake/fix-macos-libs.sh

The macos library linkage to wxWidgets is broken: cmake uses absolute library paths, but the bulid library paths does not match the runtime paths -> plugin does mnot link correctly to wxWidgets in runtime.
Add a build step which changes any wxWidgets library path to the correct runtime dir /Applications/OpenCPN.app/Contents/Frameworks using the install_name tool. Seems that macos a  tool specifically designed for this purpose. One might wonder why...

macos wxWidgets link issues

---

ci/git-push
cmake/PluginSetup.cmake

#72 is at least about the fact that gtk3 builds are not marked as such, using the same target as gtk2. This should be fixed by this PR. Whether this is  enough to actually fully resolve #72 remains to be investigated.
Also: minor cleanup in git-push, making a clean exit if there is no private key (i. e., the new-credentials program hasn't been run).

Ubuntu: fix gtk3 builds (#72)

---

ci/upload.sh.in
cmake/PluginSetup.cmake

As heading says: If user sets wxWidgets_CONFIG_EXECUTABLE  on the cmake command line it must be respected

cmake: Respect wxWidgets_CONFIG_EXECUTABLE command line variable.

---

ci/upload.sh.in

If the cloudsmith keys are missing, make a clean exit with
warning message instead of a hard failure.
Closes: #69.

Don't fail hard on missing deployment keys (#69).

---

cmake/Metadata.cmake

Creates tarballs and metadata named like ShipDriver-2.5-ubuntu-16.04. 
The major-minor spec is the compatibility level - as long as they the same the different versions are compatible. The complete version, including git commit, is available in the tarball name and in the Cloudsmith metadata (very visible when listing builds), so adding this also to the main name will probably just obscure things.
Closes: #68

Add major.minor to build ids (#68).

---

ci/circleci-build-debian.sh
ci/circleci-build-flatpak.sh
ci/circleci-build-macos.sh
ci/circleci-build-mingw.sh
ci/circleci-build-raspbian-armhf.sh

As heading says: Make sure the builds are verbose to ease debugging.
Closes: #70

build: Make builds verbose (#70).

---

.circleci/config.yml
CMakeLists.txt
appveyor.yml
ci/circleci-build-debian.sh
ci/circleci-build-flatpak.sh
ci/circleci-build-macos.sh
ci/circleci-build-mingw.sh
ci/circleci-build-raspbian-armhf.sh
ci/travis-build-raspbian-armhf.sh
ci/upload.sh.in
cmake/Metadata.cmake

Too many build fixes for a package meant to stabilize. Mostly due to changing environment (?)
- A few errors spotted while reading the code
- The changed download links: https://github.com/OpenCPN/OpenCPN/issues/2125
- Handle changes in how brew downloads packages, in particular a very expensive need to perform perforn  _git fetch --unshallow_  on brew clones
- Handle changes how the cloudsmith python installation behaves, in particular use the script which is the official entrypoint rather than _python3 -m cloudsmith_cli_
- Handle scripts installed in locations not in $PATH using a .uploadrc file.
- Streamline the python cryptography installation, use --user which avoids problem when installing system-wide. 
- Fix a bug where the version selected by _pyenv local_  wasn't found and used …

Fixes for broken links, changed python deps and what not.

---

appveyor.yml

Remove all unused 64-bit python versions and move the installation
of cryptography to the inital, setup part.  Enough to get it working.
Closes: #88

ci:appveyor: Fix git-push dependency installation  (#88).

---

ci/circleci-build-macos.sh

Nasty error, only shows up if cache is invalidated i. e., after changes
in ci/circleci-build-macos.sh. This means while things built fine by me, they failed by you.
This *should* fix  the macos issue (knock, knock...)

ci: macos: Fix missing bash function (#88).

---

CMakeLists.txt
appveyor.yml
ci/upload.bat.in
ci/upload.sh.in

Use a windows bat-file instead of a bash script on windows, and drop the git-bash dependency.
Closes: #93

Appveyor no bash (#93)

---

cmake/PluginInstall.cmake
cmake/Targets.cmake
flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml

Use a cmake batch file instead of trllions of targets to get a sequential flow.
Closes: #95

cmake: Clean up messy targets definitions (#95)

---

.cmake-format.yaml
cmake/Targets.cmake

Using this, and the cmake-format utility cmake files can be automatically formatted to the style we use.

Add .cmake-format formatting options file.

---

ci/circleci-build-flatpak.sh

Use a wildcard instead. Should make the file generic.

ci: flatpak: Don't hardcode the manifest filename.

---

README.md
appveyor.yml
cmake/Targets.cmake

Next attempt to clean up the mess in cmakeTargets.cmake w r t how targets are defined. Drops some lines, and make IMHO the code much more clear.
And yes, this time it builds in Windows. Please note that the description for #107 is somewhat misleading, it's obvious from the build log that it fails in an early stage (and that silly, silly cmake just continues despite errors...). Anyway, this should be fixed in this PR.
While on it, simplify the windows build recipe.

Windows: fix the targets rewrite

---

BUILD_DEPENDENCIES.md
buildwin/win_deps.bat
ci/circleci-build-macos.sh
cmake/Targets.cmake

Please modify this PR. My idea is that the BUILD_DEPENDENCIES.md info  should live in the wiki, it's hard to maintain multiple copies in different plugins. OTOH, submitting a file in a PR is the best way I know to forward in to you. So please remove this file, possibly after including useful parts in the wiki.
The windows batch file and the macos ci fix is ok though, I think. The macos patch is extremely dirty, we might need to have a fresh look at it.

build: Local build support, docs and windows batch file (#98).

---

CMakeLists.txt
ci/circleci-build-debian.sh
ci/generic-build-raspbian-armhf.sh
cmake/PluginCompiler.cmake
cmake/PluginLibs.cmake

PluginLibs contains more copy-pasted copy which just doesn't make sense: It locates the IOpenGL libraries, but does not link to them. Fix this, let PluginLibs both locate and link to OpenGL.
While on it: various cleanup and a fix for latest python pip 21.0.0 which is broken, crashes directly on invocation.

Opengl  update for cmake/PluginLibs

---

cmake/fix-macos-libs.sh

As heading says: Use relative library  paths instead of absolute. This will make the paths sane even if OpenCPN is installed in a non-default location.
Closes: #125
EDIT: Circle ci bulid logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/736/workflows/eb2a53fe-8344-4ace-b582-5aa3c65e9a72)

build: macos: Don't hardcode library paths (#125).

---

.circleci/config.yml

As heading says: make circleci builds opt-out rather than opt-in w r t branch names.

ci: circleci: Build all branches besides tmp and tmp-*

---

cmake/PluginInstall.cmake
cmake/Targets.cmake

As heading says: make sure that Release and MInSizRel builds strips the plugin library file.
Closes: #140

cmake: Targets, PluginInstall: flatpak strip fix (#140).

---

.circleci/config.yml
ci/circleci-build-debian.sh
ci/circleci-build-mingw.sh
ci/generic-build-raspbian-armhf.sh

Basically trying to cope with version requirements from the cryptography
and cloudsmith-cli python modules which are reflected in requirements
on python3-pip and python3-setuptools. It builds, but it is still a
mess.
Circle ci build logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/772/workflows/1b6183c9-ead1-45ec-bbd4-34134ffe6ff9)

ci: Python mess update.

---

appveyor.yml
ci/circleci-build-macos.sh

Change the one and only line which needs editing when used in
another plugin. With this change, there is one file less to edit
when adapting files to a new plugin.

appveyor: Make file generic.

---

CMakeLists.txt
shipdriver-plugin.xml.in

To the price of just a few extra lines in CMakeLists.txt the .xml.in
file can be made fully generic. Less documentation and error-prone
manual steps make this change pay off despite some otherwise
needless lines in CMakeLists.txt

shipdriver-plugin.xml.in: Make it generic

---

ci/circleci-build-debian.sh
ci/circleci-build-macos.sh
cmake/PluginCompiler.cmake
cmake/Targets.cmake

The simple "make tarball" breaks on platforms where the default number
of processors fills the available memory. Reported on arm builds.
The CI builds has walked around this by setting the processor count
using make -j $count. This works, but is not that user-friendly.
Define a new NPROC option used to define processor count with
hopefully sane default values, including respecting the
documented CMAKE_BUILD_PARALLEL_LEVEL
Fix is already applied and tested in radar_pi.

cmake: Define number of processor in configure time.

---

cmake/PluginLibs.cmake

As discussed in zulip: Warn if windows user hasn't run win_deps.bat

PluginLibs: Windows: Warn if win_deps.bat has not been run.

---

cmake/Metadata.cmake

Don't label armhf packages as A64 (#169).

---

.circleci/config.yml
ci/circleci-build-flatpak.sh

Build the three flatpak variants for 5.6.0: aarch64/20.08, x86_64/18.08 and x86_64/20.08.
This is ported from upcoming o-charts_pi, the successor of oesenc_pi. The build routines have been tested and should be reasonably stable.
Closes: #175

ci: Update flatpak builds (#175).

---

ci/circleci-build-flatpak.sh

Make sure that builds for runtime 18.08 don't uses upcoming 20.08
releases on the stable branch. This is achieved by locking down
the build to use to the last known 18.08 ostree commit.
Closes: #177

ci: flatpak: Pin the 18,08  opencpn release.

---

cmake/Metadata.cmake

The upload repository is in many cases an environent variable. Some
builders treats all such variables as secrets and does not display
them in the log. Make sure they displayed anyway by inserting blanks
between each character.

Make sure upload repo is displayed (#180).

---

ci/upload.sh.in
cmake/Metadata.cmake

This patch:
- Restores the the way to get the tag related to current HEAD
- Adds working debug printout of the upload repo in the upload script

ci: Print upload repo on builders hiding env vars (#180).

---

ci/circleci-build-flatpak.sh
flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml

The reason for the hang in the build as of #187 was a simple bug, my bad.  However, it's time to make a major overhaul of the flatpak builds afte4r the update to 20.08 runtime. Notably, without fixes here local builds fails.

Flatpak: bugfix, update for 20.08 runtime

---

.circleci/config.yml
ci/circleci-build-flatpak.sh

Hopefully, the last bugfix. First id didn't build 18.08, then it always built 18.08. This time, 18.08 should be built as it should. 
Sigh

Ci flatpak 187 v3

---

.drone.yml
ci/upload.bat.in
ci/upload.sh.in
cmake/Metadata.cmake
plugin.xml.in

A new stab on #193 which:
- Adds a link to the build log as a comment in the metadata files.
- Cleans up the filename for tagged builds, basically just using the tag as identifier (besides target platform).
- Allow overwrites when uploading, last upload wins if there are two files with the same name.
Everything should still be possible to trace, the auto branch will have copies of all versions of the metadata files since the build comment differs.
We need to think more about this.... Thoughts?

Filenames and such

---

cmake/Metadata.cmake

For tagged builds, name the metadata file similar to to the tarball: Replace version with the tag name.
As always, there is room for refactoring and cleanup.

cmake: Metadata: Use the tag name also for metadata, refactor.

---

libs/jsoncpp/CMakeLists.txt

As I suspected the linkage error was simple bug. I have not built this, so we need to wait for builders before merging.

libs/jsoncpp: Dont use system library by default.

---

.gitignore
UPDATE_TEMPLATES.md
update-templates

Close some open issues:
- Update bootstrap info to reflect that script is merged into rasbats/shipdriver
- Add  a provisionary UPDATE_TEMPLATES.md document.
- Add some windows usage notes
- Support a blacklist (update-ignored) which lists files which should not be updated.
- Use current branch rather than hardcoded master as the branch merging changes
- Add a *treeish* option to script so one can merge changes from a specific shipdriver commit or tag rather than just shipdriver/master.
While on it: some .gitignore updates.
See: #201

Update-templates: Update (#201)

---

UPDATE_TEMPLATES.md
update-templates

Added what I think is the last missing pieces (?):
- Added a -t option and changed the default setup to don't use `-X theirs`. *update-templates -t* basically does the same thing as *update-templates* before the change. See UPDATE-TEMPLATES.md
- Added self-updating. This means that we add the update script to the plugin repos, but the script will update itself before running.  I think it's pretty easy to use and also avoids complicated curl commands except for the first time.  It make things sane since the repo is totally clean when running the update. More in UPDATES-TEMPLATES
- Bugfixes and cleanup.,

Update rev3 (#201)

---

CMakeLists.txt
cmake/PluginOptions.cmake

While on it, refactor the general options handling to a separate
file, to avoid maintaining to much in CMakeLists.txt which is
outside the template set.
Closes: #207

CMakeLists, PluginOptions: Handle undefined CMAKE_BUILD_TYPE (#207)

---

ci/circleci-build-macos.sh

This was somehow lost in  the process, sorry... No point to try to create target pkg on macos anymore.

Don't try to build macos pkg target (#205).

---

UPDATE_TEMPLATES.md
update-templates

For CMakeLists and the flatpak manifest: add the changes in the
upstream shipdriver file as comments to the downstream variants
as help to fo update these.
This is basically to automate the instructions in UPDATE-TEMPLATES which thus  are simplified.

update-templates: Handle upstream changes in CMakelists etc.

---

CMakeLists.txt

Turned out that the error which was visible on MacOS actually was present on all platforms. The fix is simple, though.

Cmakelists refactoring: MacOS build fix

---

cmake/PluginCompiler.cmake
cmake/PluginOptions.cmake

After refactoring the separate Plugin.cmake file the code to set up
OCPN_NPROC was executed after it was used. Fix that.
Closes: #290

cmake: Make sure OCPN_NPROC is available from the beginning (#290)

---

ci/circleci-build-macos.sh

Update deployment target after discussions in upstream bug.
Closes: #286

ci: macos: New deployment target 10.10 (#286)

---

CMakeLists.txt

... glob it instead. Might fail if user has multiple matches, but that seems very unlikely
Closes: #289

Avoid hard-coded flatpak manifest path (#289)

---

ci/circleci-build-macos.sh

Fix builds for macos (did git submodule update --init at the wrong point.)

ci: macos: Dont forget to initialize submodule.

---

.circleci/config.yml

For circleci, limit the number of CPUs used to 2.
The underlying problem here is a bug in docker which when client asks for number of CPU:s available get the total number of CPUs in the host rather the cpu count available in the docker guest. Not much to do than to manually limit.
Closes: #301

ci: circleci: Limit CPUs used (#301).

---

libs/jsoncpp/CMakeLists.txt
libs/jsoncpp/src/lib_json/json_reader.cpp

Back-port fix for the build error in jsoncpp from #298

jsoncpp: Apply patch muting bogus diagnostics (#288).

---

buildwin/win_deps.bat
cmake/Targets.cmake

Make flatpak, windows and since earlier Android builds us a common cache directory for downloads and other state. This means that the cache persists even if the build directory is cleared and also avoids cluttering for example c:/ top directory with various downloads.
Might be other things to handle before closing #312, but this should be a good starter. Builds on all hosts and does not cause any changed behaviour in local builds.

#312: Move temporaries to project cache directory.

---

Changelog.md

As heading says. Please update the first line (beta 2 release date) when making the beta2 tagging.

docs: Add a ChangeLog.

---

cmake/PluginLibs.cmake

As heading says: Nuke traces of wxWidgets 2.8 `wxWidgets_USE_LIBS` and make sure that we link the gl component when available.
Closes: #332

PluginLibs: Fix handling of wxWidgets components (#332)

---

CMakeLists.txt

This should be acceptable as a clean bugfix. It will not add the
wxjson subdirectory twice, the root problem in #330.
The catch is that semantics will change: A plugin which links to
jsoncpp will fail since josncpp will not be visible until all plugins
are linked.
However, I'm not aware of any plugin which depends on jsoncpp. And
if there indeed is such a plugin, it can be handled by Plugin.gl
by adding jsoncpp before. This is a lesser evil than the current #330
situation
Closes: #330 -- the repeated build issue reported there is in #331

CMakeLists: Only link libjsoncpp if not done by Plugin.gl (#330).

---

CMakeLists.txt
Changelog.md
appveyor.yml
buildwin/win_deps.bat
cmake/PluginLibs.cmake

- Drop old, lingering MSYS patch in PluginLibs.cmake
- Like in Debian builds, use the same script win_deps.bat in both CI and "manual" builds. Clean up appveyor.yml.
- Drop the special handling of the jsoncpp library, the root cause behind #330, partially fixed in 3.0  branch

Updates to master branch

---

update-templates

Refuse to run without arguments. Enhance help message and make it
focus on using tags.
Closes: #366

update-templates: Don't default to shipdriver/master (#366).

---

scripts/local-build.rc

A hopefully better alternative to #368. No Caps Lock, and a
more balanced tone. More emphasis on the workflow: first copy, then edit.

local-build.rc: Update comments (#368).

---

.circleci/config.yml
Changelog.md
UPDATE_TEMPLATES.md
ci/circleci-build-flatpak.sh
cmake/Metadata.cmake
cmake/Targets.cmake
flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
scripts/local-build.rc
update-templates

Cherry-picked fixes from master:
- Actually use tag as version (#349).
- update-templates is basically brought to same state as master, besides opencpn-libs submodule. Lot's of fixes.
- Flatpak ci changes updated to master, they reflects the OpenCPN 5.6.0 release.
- Some documentation fixes.
Hopefully, this should not break any eggs while actually fixing some bugs. If OK with you I suggest that we tag this as v3.0.1-beta1 and then makes some further testing

V3.0: tentative v3.0.1-beta1

---

ci/circleci-build-flatpak.sh
ci/generic-build-raspbian-armhf.sh

As heading says: fix sort  of typo errors in the ci scripts.
I think this should fix the issues in #383. However, cloudsmith is currently down and all builds fail in the upload phase.  
The cloudsmith status is available in https://status.cloudsmith.io/.  I have been in contact with their support which basically says we have to wait until the incident reported for January is resolved before things start top work again.

ci: flatpak, raspbian: Fix (sort of) typo (#383)

---

.circleci/config.yml
ci/circleci-build-debian.sh

Since they don't work, remove them for now. 
This is possibly  not the last word on #399, but considering all the new build stuff in the pipe we probably just don't have the manpower to also maintain outdated, unsupported xenial any more
New try without any opencpn-libs stuff.

Drop xenial builds (#399).

---

.circleci/config.yml
ci/circleci-build-bionic-armhf.sh
ci/circleci-build-focal-armhf.sh

Last part of Dave's work on o-charts_pi which builds the new ubuntu-{focal,bionic}-armhf targets instead of corresponding Raspbian ones. And a small patch from me which makes it really faster :)
Closes: #380
Kudos: @bdbcat

Build ubuntu armhf targets (#380)

---

buildwin/win_deps.bat

Use the pathman tool to set PATH in the registry rather than the
current session. Besides that the PATH set now is persistent
pathman also ensures that path elements are not duplicated.
There seems to be some changes in how Windows handles PATH
lately, not sure. The fixes are hopefully sound anyway.

win_deps.bat: Make PATH handling more consistent.

---

update-templates

Add config.h.in and build-deps if these does not exist. In other cases don't touch them, this data is private for the plugin.
Makes a better starting point when applying script to new plugin.
Might or might not close #405

update-templates: Add missing private data if required (#405)

---

INSTALL.md
buildwin/minimal-path.bat
buildwin/win_deps.bat
cmake/AndroidLibs.cmake

Create a tested build baseline on Windows which does not depend on user's %PATH%.
New file _minimal-path.bat_ and updates to _INSTALL.md_
EDIT: And a totally unrelated fix to the Android builds -- Dave ha updated the library blob and the hash needs to be updated

Win build fixes

---

.circleci/config.yml

Add a Debian 11/Bullseye build. That it is missing seems to be some sort of oversight, it is required when handling the "Debian plugins everywhere" roadmap.
We'll get a  *lot* of builds until 5.6.2 is release in March at which point we can start dropping unneeded builds.

ci: Add a Debian Bullseye build.

---

buildwin/win_deps.bat

Use the pathman tool to set PATH in the registry rather than the
current session. Besides that the PATH set now is persistent
pathman also ensures that path elements are not duplicated.
There seems to be some changes in how Windows handles PATH
lately, not sure. The fixes are hopefully sound anyway.

win_deps.bat: Make PATH handling more consistent (v 3.0 update).

---

Changelog.md
update-templates

The new OpenCPN release 5.5.2 is looming, ETA is  "March". Before that we need to have at least the new builds in master branch available.
All relevant issues are closed. IMHO, it's time to start testing 3.1.0 by merging this PR, updating the date in the changelog  and tag it as sd3.1.0-beta1.
Thoughts?

Changelog: Prepare 3.1.0-beta1 release

---

.circleci/config.yml
Changelog.md
ci/circleci-build-ubuntu-armhf.sh

The  ubuntu-wx31 build is ahead of the development at opencpn/plugins and should be dropped for now.
Handle updated ubuntu repos by adding the proper key to the keyring to make sure the update runs correctly.
Closes: #437 
Unless more issues are pending, please tag  as sd3.1.1 after merging.
EDIT: As usual, please update Changelog.md before tagging.

Builds: Handle updated ubuntu repo key, drop obsolete ubuntu-wx315 build

---

Changelog.md
Plugin.cmake

Update opencpn-libs -- changes for disabling useless warnings. LIbraries now builds cleanly.
Initiate branch top be about upcoming 3.2.0 (Plugin.cmake, Changelog).

opencpn-libs: Clean up compiler warnings.

---

update-templates

As heading says: let update-templates remove unused .drone.yml to avoid build errors.

update-templates: Remove unused drone.yml  (#380, #217)

---

INSTALL.md
flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml

The major taks here is that a alpha version of OpenCPN now is available in the flathub beta branch. Update manifest to use the beta branch and thus build against wx32 as planned 
EDIT: Due to new git behaviour  plugging a security hole there are updated instructions how to build  flatpak. See INSTALL.md.

Flatpak: Update to build against wxWindows 3.2  (#458)

---

.circleci/config.yml
ci/circleci-build-flatpak.sh
update-templates

**Note:** After applying these changes we don't build any more plugins for O56. This should basically be OK, but we need to leave the existing O56 plugins in the catalog rather than replacing them with the O58 ones.
During the beta period until O58 is release we will have to build flatpak plugins against the flathub beta branch, this is the only one which is linked against wx-32. Also, this is of course the closest we can get to upcoming O58.
The build manifest needs to be updated with correct runtime-version (22.08) and runtime branch (beta). For local builds, this is done by update-templates.
For the CI builds the manifest is patched by the build script, so it does not need to be updated. In other words, it should work out of the box for existing plugins, updated or not.

Flatpak wx32: Clean up build scripts.

---

.circleci/config.yml
ci/circleci-build-debian-armhf.sh
ci/circleci-build-debian-docker.sh
ci/circleci-build-debian.sh
ci/download-wx32.sh

According to discussion in https://github.com/OpenCPN/OpenCPN/discussions/2797 we need to add three builds for Debian 11/Bullseye which are linked against wxWidgets 3.2 -- this makes the plugins work for O58 on Focal and Bullseye.
WxWidgets3.2 and the the wxsvg library are backported and rebuilt  for all three platforms and are available at https://cloudsmith.io/~alec-leamas/repos/wxwidgets/. 
The builds here downloads these libraries and builds using them. It's an awful hack, but it's a one time shot: from Bookworm/Debian 12/Ubuntu 24.04  the proper libraries will be available in Debian/Ubuntu repos.

Debian: Add wx32 (wxWidgets 3.2) builds for bullseye (OpenCPN#2797).

---

appveyor.yml
buildwin/win_deps.bat
ci/windows-ldd

- Update to Visual Studio 17 2022
- Use the provided python, no need to use choco to get a recent version
- Fix broken pathman installation

ci: windows: Update to VS 2022, use bundled python 3.10

---

build-deps/0001-matrix.h-Patch-attributes-handling-wxwidgets-22790.patch
ci/circleci-build-debian-armhf.sh
ci/circleci-build-debian-docker.sh
ci/circleci-build-debian.sh

Apply a patch for the specific use case  in matrix .h which we use. This is supposed to become fixed in wxWidgets 3.2.3, but needs to be patched utnil then.
See: https://github.com/wxWidgets/wxWidgets/issues/22790

ci: debian: Add patch for matrix.h (wxwidgets#22790).

---

CMakeLists.txt

As heading says. This is a temporary  quick fix which even if it works should be replaced with something cleaner.

CMakeLists: Use a different project name when using wx32.

---

.circleci/config.yml
.gitignore
CMakeLists.txt
build-conf.rc
ci/circleci-build-android.sh
ci/circleci-build-buster-armhf.sh
ci/circleci-build-buster.sh
ci/maybe-push-upload.sh
update-templates

After discussions with @bdbcat, add two new builds for buster-x86_64 and buster-armhf.
The basic position on Buster builds is that  the catalog is frozen, and that new builds not goes into the catalog. However, in rare cases there might be a need to issue critical bug fixes also for buster a. k. a. oldstable. 
This means that while the catalog basically is constant w  r  t Buster builds we should still keep the possibility to make Buster builds which are used on Bionic.
To that end the builds here are governed by a  new config file _build-conf.sh_. The default setup is to make a build every tenth run without uploading anything. This can be modified as needed in _build-conf.sh_.

CI: Add configurable Buster builds.

---

CMakeLists.txt

I have added your .lib to api-16 and api-17 in opencpn-libs. No headers are  updated, there should by definition not be any changes in them up to level 17.
Since "your" lib obviously is recent enough to support api-17 it also covers api-16.
A related issue is a need to add a more recent API level. Time will tell.

Use correct windows library (wx30 vs wx32)

---

CMakeLists.txt

As heading says: Using a separate name for the wx32 package seemed like a good idea, but it was not. Hopefully, this makes the wx32 package installable.

CMakeLists: Don't use different package name for wx32

---

.circleci/config.yml

As heading says: Don't build debian-bullseye-armhf twice.

.circleci/config: Remove duplicated bullseye-armhf entries

---

.circleci/config.yml

circleci: Add missing build build-bullseye-wx32-armhf (#481).

---

ci/appveyor.bat

Instead if blindly hardcoding the assumed path to Visual Studio use official mechanisms to resolve it. Instead of using the more or less deprecated  vcvars32.bat use the modern VsDevCmd.bat, available since VS 2017.
This is as used in main OpenCPN.

ci: appveyor: Handle different VS locations.

---

ci/appveyor.bat
ci/circleci-build-android.sh
ci/circleci-build-flatpak.sh

A lot of signing keys are updated, perhaps due to new year, perhaps  the CircleCI security incident reported where keys was compromised.
This closes #487. As for #486, it moves things forward making it possible to add the PPA again. However, this reveals new issues hopefully resolved on the flatpak mailing list.

Signing keys (#486, #487)

---

.circleci/config.yml
cmake/MacosWxwidgets.cmake

This moves the build of wxWidgets to the project cache/ directory  for MacOS, similar to the windows approach.
If a wxWidgets 3.2  builds can be located, for example in /usr/local this is by default used. The new cmake parameter IGNORE_SYSTEM_WX can be used to force the build in cache/ if the system variant cannot be used for some reason.
Closes: #495

ci:macos: Move build to local cache (#495)

---

.circleci/config.yml
ci/circleci-build-debian-armhf.sh
cmake/MacosWxwidgets.cmake

#498 is actually an odd  corner case, triggered only on builds tagged with a beta tag AND using the CLOUDSMITH_BETA_REPO environment variable to relocate the upload repository. In short, it probably only hits me.
Closes: #498

Debian armhf builds: Fix handling of CLOUDSMITH_BETA_REPO environment var (#498)

---

ci/circleci-build-buster-armhf.sh
ci/circleci-build-debian-armhf.sh
ci/circleci-build-debian-docker.sh
ci/circleci-build-debian.sh
ci/circleci-build-flatpak.sh
ci/circleci-build-macos.sh
cmake/Metadata.cmake

- Build debian-wx32 targets using wxWidgets 3.2.2.1 instead of wx 3.2.1.
- Build flatpak builds with 1 parallel, as I am seeing spurious make errors at 2.
- Allow override of CMAKE_BUILD_TARGET for local builds.

Use wxWidgets 3.2.2, verify checksums, fix flatpak

---

cmake/Metadata.cmake
cmake/PluginSetup.cmake

This patch makes any Linux machine generate usable plugin metadata with target correctly including the architecture, regardless of the distribution used. It makes development and testing on "unsupported" systems, eg. Fedora a tad simpler as the locally built plugin artifacts are directly usable in locally built OpenCPN.

Generalize target name generation on Linux

---

Changelog.md

The cloudsmith pythonpackage is incompatible with version 2.0.0 of urllib3, released end of April. Lock urllib2 to be < 2.0.0 until cloudsmith has updated their package
Closes: #520

debian upload: Don't use updated urllib3 libary

---

Changelog.md
ci/circleci-build-debian-armhf.sh
ci/circleci-build-debian-docker.sh
ci/circleci-build-debian.sh
cmake/CmakeSetup.cmake

The cloudsmith python package is incompatible with version 2.0.0 of urllib3, released end of April. Lock urllib2 to be < 2.0.0 until cloudsmith has updated their package

Use urllib < 2.0.0  (#520)

---

cmake/Metadata.cmake
cmake/PluginSetup.cmake

Drop some debugging statements added in #541 since they no longer are useful.
If we overall did log at this level the configuration output would become unlegible. Less is more...

PluginSeup, Metadata: Remove temporary debug logging.

---

.circleci/config.yml
cmake/Metadata.cmake
cmake/PluginSetup.cmake

- Fix cmake logging of target:release 
- Remove horrible hack for not longer used ubuntu targets
- Update OCPN_TARGET_TUPLE for all debian targets

Targets update  (#540).

---

cmake/Metadata.cmake

The  fix in #541 does the wrong thing when using OCPN_TARGET_TUPLE. Revert it, to keep things consistent.
This will create the wrong target when doing a plain `cmake ..` in  local build. However, this is less of a problem, we can live with that for now until we have a better fix.

Metadata.cmake: Revert bad fix in #541  (#540)

---

.circleci/config.yml
ci/circleci-build-android.sh
cmake/AndroidLibs.cmake
cmake/android-armhf-toolchain.cmake

- Update the deprecated circleci android images.
- Update the  mega blob used for linking the plugins to API 1.18

Update android builds

---

cmake/PluginCompiler.cmake

C++14 matches core opencpn settings and is fully supported by compilers since long.

Compiler: C++ standard: C++11 -> C++14

---

Changelog.md
Plugin.cmake

This update break the inclusion of opencpn/plugingl. Any plugin using this needs to apply the following patch
-  add_subdirectory("${CMAKE_SOURCE_DIR}/opencpn-libs/plugingl")
-  target_link_libraries(${PACKAGE_NAME} ocpn::plugingl)
+  add_subdirectory("${CMAKE_SOURCE_DIR}/opencpn-libs/plugin_dc")
+  target_link_libraries(${PACKAGE_NAME} ocpn::plugin-dc)
Furthermore, plugins including opencpn/glu should remove this, it is included in the new plugin_dc library.

opencpn-libs: Update to current main

---

FIX_PLUGIN_INFO.md
config.h.in
src/ShipDriver_pi.cpp

The current implementations of  `GetCommonName()`, `GetShortDescription()` and `GetLongDescription()` are basically broken . If they were sane they would return the data in Plugin.cmake which is used in the catalog.
However, they don't. Instead they return  some more or less random data which is hard to maintain.
Until now this has not been that important, after all almost all visible content is taken from the catalog. Upcoming changes makes this more of a problem and we need to fix this. This is a tentative patch which perhaps could need some polish.
Note the new  FIX_PLUGIN_INFO.md. The work done in this patch needs to be applied manually in each plugin using the template.
Closes: #572

config: Use Plugin.cmake data in plugin API (#572)

---

cmake/GetArch.cmake

Follow up to #573. The value from GetArch is currently not used, but updated for consistensy.

cmake/GetArch: Return correct x86 on windows (#573)

---

buildwin/win_deps.bat
ci/circleci-build-debian-armhf.sh
ci/circleci-build-debian-docker.sh
ci/circleci-build-debian.sh
cmake/MacosWxwidgets.cmake

Update the bundled wxWidgets version used in various builds to 3.2.4.
Bookworm uses the system libraries which are on 3.2.2, no plans to change that. This means that the outdated bullseye builds have a more recent version than bullseye. Interesting... 
Closes: #564

Update wxWidgets build dependencies

---

.circleci/config.yml
build-deps/macos-deps
ci/circleci-build-flatpak.sh
ci/circleci-build-macos.sh

Update images used for Linux, flatpak and macOS builds to the latest available as CCI is phasing out support for the currently used ones.

CI images update

---

.circleci/config.yml
ci/circleci-build-flatpak.sh
flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
update-templates

The default runtime used when building Flatpak is as of flatpak/org.opencpn*.yaml. Hence, building with 24.08 must use something like -DOCPN_TARGET_TUPLE="flatpak-x86_64;24.08;x86_64"

Flatpak: Add new 24.08 beta builds  (#598)

---

ci/circleci-build-flatpak.sh

The default runtime used when building Flatpak is as of flatpak/org.opencpn*.yaml. Hence, building with 24.08 must use something like -DOCPN_TARGET_TUPLE="flatpak-x86_64;24.08;x86_64"
Smoke test using  the OpenCPN beta OK.

Flatpak: Add new 24.08 beta builds - part 2 (#598)

---

ci/circleci-build-debian.sh

The need to restore the build dir permissions is actually only on non-CI builds. Avoid problems which occurred after the Bullseye containers updated default permissions by leaving the CI build dir open on CI builds.
Closes: #602

ci: Handle changed bullseye container permissions (#602)

---

src/shipdriver_gui_impl.cpp
src/shipdriver_gui_impl.h

Removed extraneous "," after "T" in HDT
Removed unused and useless wxStrings   
Added Kph speed to complete the sentence
Added a macro to convert knot to kph
Removed unused and useless wxStrings 
Added feet and fathoms depths to  complete the sentence
Added a macro to convert meter to feet and meter to fathom
Changed depth value to 10
Moved NMEA sentence example inside the createDBT( ) like for every other functions.
Removed unused and useless wxStrings 
Merged commits of 28/06/2025 (v3.4.2 to v3.4.4)

Fix HDT & Add missing values to VTG, VHW, DBT
