- po/ar_SA.po
- po/ca_ES.po
- po/cs_CZ.po
- po/da_DK.po
- po/de_DE.po
- po/el_GR.po
- po/es_ES.po
- po/et_EE.po
- po/fi_FI.po
- po/fr_FR.po
- po/gl_ES.po
- po/hu_HU.po
- po/it_IT.po
- po/ja_JP.po
- po/nb_NO.po
- po/nl_NL.po
- po/pl_PL.po
- po/pt_BR.po
- po/pt_PT.po
- po/ru_RU.po
- po/sv_SE.po
- po/tr_TR.po
- po/vi_VN.po
- po/zh_TW.po
This is what we've got so far. Nothing new added for a week or so.
> New po-files from Crowdin

- .travis.yml
- appveyor.yml
for cloud based checking of commits
> ov50 - add appveyor.yml and .travis.yml

- appveyor.yml
> appveyor.yml fix path

- ci/circleci-build-debian.sh
- ci/circleci-build-macos.sh
- ci/travis-build-raspbian-armhf.sh
- cmake/GetArch.cmake
So, let's also actually build the metadata. Rebasing is risky business, but I needed this history to be sane...
> Fix metadata2

- cmake/metadata.cmake
- shipdriver-plugin.xml.in
This was mostly a new and interesting (well..) issue with flatpak. Now it seems to work, at least for me  i. e., flatpak.
> Metadata fixes

- cmake/PluginPackage.cmake
So: just make sure that make pkg does not overwrite any tarball by makin git creating a zip archive instead.
> cmake: macos: Don't allow 'make pkg' to overwrite tarball.

- DEPENDENCIES.md
- README.md
A first try. Please don't forget to fix the errors you see...
> Deps 98: Updated dependencies docs

- libs/tinyxml/CMakeLists.txt
- libs/wxJSON/CMakeLists.txt
Ouch... how did that slip through? Sorry, but here is the fix.
> libs: Fix a bad typo.

- cmake/Targets.cmake
Make repeated builds like make tarball; make tarball work. 
Closes: #121 
Circleci build logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/716/workflows/8e8d948a-ea5a-4432-a2e8-64d0412079fe)
> Make sure repeated builds work

- ci/circleci-build-mingw.sh
- ci/generic-build-raspbian-armhf.sh
In this PR:
- Bugfixes w r t travis builds.
- Cleanup the docker handling which contained lot's of copy-pasted cruft.
> CI: Docker cleanup, travis buildfixes.

- .circleci/config.yml
- ci/github-build-flatpak.sh
> ci: .circle/config: bugfix.

- buildwin/win_deps.bat
> win_deps.bat: Fix missing path element (#161).

- .circleci/config.yml
- CMakeLists.txt
- ci/circleci-build-android-arm64.sh
- ci/circleci-build-android-armhf.sh
- ci/circleci-build-macos.sh
- cmake/PluginCompiler.cmake
- cmake/PluginLocalization.cmake
- cmake/Targets.cmake
- libs/AndroidLibs.cmake
Upstreamed changes from o-charts + new android builds.
> CI: Add android builds

- cmake/PluginLibs.cmake
As heading says: simple bugfix. Question is how this happened...
> cmake/PluginsLibs: bugfix

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
actually build  the 18.08 stuff...
> ci: circleci: Actually build the x86_64/18.08 stuff.

- UPDATE_TEMPLATES.md
Just some final remarks in UPDATE_TEMPLATES
> UPDATE-TEMPLATES: polish.

- CMakeLists.txt
- Plugin.cmake
- plugin.xml.in
Make the api level configurable to resolve #280. Also, remove the clumsy, misleading CPACK\_* variable names (#282)
Closes: #280 
Closes: #282
> Plugin configuration fixes (#280, #282)

- INSTALL.md
Small update, notably change the managed_plugins link from the wiki to the manual.
> INSTALL.md: Documentation update.

- .gitignore
- ci/git-push
- scripts/local-build
- scripts/local-build.rc
- scripts/local-upload
Added documentation, see https://github.com/Rasbats/managed_plugins/pull/18
Fixed a number of bugs, partly due to insuffient testing on Windows, partly since two of my earlier PR broke when they were combined, partly to enhance on-line docs. Nothing here should be controversial
> Local build: clean up and bugfixes.

- CMakeLists.txt
- Plugin.cmake
The project name should be defined in Plugin.cmake together with
version etc.
Closes: #320
> Don't hardcode project name (#320).

- CMakeLists.txt
- Plugin.cmake
- cmake/PluginLibs.cmake
- update-templates
Simple bug fixes, see commit comments.
> Fix issues #323 and #324

- UPDATE_TEMPLATES.md
As heading says. After merging, please review and add fixes for whatever things I missed.
> UPDATE_TEMPLATES.md: Update (#327).

- Changelog.md
> Update Changelog to include the 3.0.0 release

- CMakeLists.txt
- cmake/Targets.cmake
- update-templates
As heading says: fixes for #331 and #336.
As for  repeated make I'm pretty confident that it is solved. update-templates needs more testing, testing which is easier to do if it's merged. That said, I have successfully run it on a non-shipdriver plugin.
> Fixex for issues #331 and #336

- update-templates
Bugfix. update-templates needs more testing...
> update-templates: Don't forget to update buildwin (#133).

- .circleci/config.yml
- ci/circleci-build-flatpak.sh
- cmake/Metadata.cmake
- cmake/Targets.cmake
- flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
Fixes for a number of flatpak-related problems + version handling. Please see commit comments for details
> Flatpak tags

- UPDATE_TEMPLATES.md
- update-templates
Fix #358, don't create an unused work branch (old left-overs) and clean up some if-then.
Closes: #358
> update_templates: Handle #358

- update-templates
> update-templates: Copy also libs for now (#360).

- update-templates
- Fix a options string typo
- Make sure not all tags are downloaded from shipdriver
- Handle missing shipdriver remote when doing -l
> Update-templates fixes

- UPDATE_TEMPLATES.md
- update-templates
Notes in the script to use latest available stable tag, and an overhaul of UPDATE_TEMPLATES.md
> docs: Update, notably on which tag to use.

- update-templates
As  heading says.
Closes: #378
> update-templates: Don't touch libs (#378)

- UPDATE_TEMPLATES.md
- update-templates
Updates to UPDATE_TEMPLATES.md and documentation parts in update-templates. No functional changes.
> update-templates: 3.0.2 updates and polish

- UPDATE_TEMPLATES.md
- ci/circleci-build-flatpak.sh
- ci/generic-build-raspbian-armhf.sh
- libs/api-17/CMakeLists.txt
- update-templates
As heading says: apply some bugfixes implemented in v3.0 also to master branch.
> Sync v3.0: Update master branch with last-minute bugfixes from v3.0

- cmake/Metadata.cmake
- cmake/PluginLibs.cmake
Dave sent us two fixes, one about OpenGL linkage and one about creating unique artifacts. As I see it a no-brainer for master, and should probably be cherry-picked into v3.0 as well.
> Fixes from o-charts_pi

- buildwin/win_deps.bat
Small fix to windeps.bat to handle non-existing python better.
> win_deps.bat: Handle uninstalled python better.

- ci/circleci-build-ubuntu-armhf.sh
I know I was looking on this when I took Dave's code, but I let it be as it was. Simple fix.
Closes: #409
> ubuntu-armhf: Don't forget 'apt update' (#409).

- Changelog.md
Update Changelog with a placeholder for 3.0.3 release.
My proposal: update date in Changelog, push and tag as sd3.0.3. OK?
> Changelog: prepare 3.0.3 release.

- .circleci/config.yml
- update-templates
It's yet not time to build focal-wx31, it must be dropped.
Closes: #444
> Drop premature focal/wxWidgets 3.1.5 setups

- appveyor.yml
- buildwin/win_deps.bat
- ci/appveyor.bat
- Actually use the proper targets msvc and msvc-wx32
- Fix dumpbin failure in first build.
> appveyor: bug fixes

- buildwin/win_deps.bat
- ci/appveyor.bat
> appveyor.bat: Only build wx32 version, drop plain 'msvc'

- Changelog.md
- build-deps/macos-deps
- ci/circleci-build-macos.sh
- update-templates
I think we have completed the necessary steps for 3.2.0 EXCEPT testing. Do you have some time for that? Of course, feel free to tag it with a beta tag.
> 3.2.0 rc1: Final polish for 3.2.0 release.

- ci/circleci-build-macos.sh
> ci: macos: Rectify metadata and tarball name (#475)

- ci/circleci-build-debian-docker.sh
> ci: debian: handle new git directory permissions check.

- Changelog.md
- ci/circleci-build-debian-armhf.sh
- ci/circleci-build-debian-docker.sh
- update-templates
> Fixes for #490 and #492

- INSTALL.md
As heading says. If you have time to check, appreciated...
> INSTALL.md: update windows build

- .gitignore
- update-templates
As heading says. I have not done a lot of testing, just the basics. If you have some time...
> update-templates: Handle MacOS sed (#505).

- .gitmodules
- update-templates
Adds multiple new libraries from the tp universe.
Also tentative changes to handle the move from leamas/opencpn-libs to opencpn/opencpn-libs. This is preliminary code needing more testing.
> opencpn-libs: Update to current main, handle move to opencpn/opencpn-libs

- src/ShipDrivergui_impl.cpp
Fix some annoying compilation warnings
> ShipDrivergui_impl: Fix compiler warnings.

- cmake/Metadata.cmake
> Metadata: drop drone builder support, add Github Actions.

- FIX_PLUGIN_INFO.md
- config.h.in
- src/ShipDriver_pi.cpp
As heading says, updated to fix FTBFS errors in previous attempt.
Closes: #572
> config: Use Plugin.cmake data in plugin API (#572)

- buildwin/win_deps.bat
- buildwin/wxwidgets-3.2.4-584.patch
- cmake/PatchFile.cmake
- cmake/PluginCompiler.cmake
Trying to get the fix from zulip into the regular build. Late here, needs testing.
> Fix wrong ABI for OpenCPN 5.8.4/wxWidgets 3.2.2.1  (#584)

- cmake/CmakeSetup.cmake
> Fix hardcoded build path (#593)
